name: desafio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1


flutter_native_splash:
  color: "#00C1AF" 
  image: "assets/img/splash.png"
  android: true
  ios: true



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/img/splash.png


  uses-material-design: true

